name: Deploy react app # Nombre del flujo de trabajo
on: # Nos permite crear eventos, en este caso las acciones se realizarán cuando se detecten cambios en la rama main
  push:
    branches:
      - master  
jobs:
  deploy:
    name: deploy app
    runs-on: ubuntu-lastest
    strategy:
      matrix:
        node-version: [ "12.x" ]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{matrix.node-version}}
        - name: install packages
          run:  npm install
        - name: registry github user
        run: /
            git config --global user.email <email>
            git config --global user.name <name>
        - name: deploy the app
        run: npm run deploy
        env:
          DEPLOY_GHPAGES: ${{ secrets.DEPLOY_GHPAGES }}
      